### PR TITLE
Added Thompson sampling

### PR DESCRIPTION
**Pull request by jkomiyama**

### CODE REVIEW

**Comment by TkrUdagawa** [comment]
Please apply this patch.
https://gist.github.com/TkrUdagawa/7a6e2ba33a450962379a

This patch includes:
- fix the test error
- fix the return value in random number generation
- support assume_unrewarded option
- follow Jubatus coding style

**Comment by jkomiyama** [comment]
applied patch.

**Comment by TkrUdagawa** [comment]
LGTM.
Thanks for your great contribution!

**Comment by kmaehashi** [comment]
Directly fixed include guard error in commit b2c881b.

**Pull request merged**
