### PR TITLE
Support build with Python 3.x

### LINKED ISSUE #30: Build fails when using Python 3.3 or later.
https://github.com/pfi/pficommon/issues/155
http://gentoo.hatenablog.com/entry/2014/07/08/112129

### PR DESCRIPTION
**Pull request by kmaehashi**
Fix #30.

* Upgrade waf-unittest module to support Python 3.3. This fix is currently proposed to waf-unittest project. Its preferable to merge this PR after https://github.com/tanakh/waf-unittest/pull/18 got merged.

### CODE REVIEW

**Comment by rimms** [comment]
I tested this patch with Python 3.4.3.

I tried to run `./waf cpplint`, the following errors are printed:
```
./waf cpplint
Traceback (most recent call last):
  File "/home/rimms/jubatus_core/.waf3-1.6.4-37059750328bf24b869521d97d29c0c1/waflib/Scripting.py", line 93, in waf_entry_point
    run_commands()
.. snip ..
  File "/home/rimms/.pyenv/versions/3.4.3/lib/python3.4/tempfile.py", line 399, in func_wrapper
    return func(*args, **kwargs)
TypeError: 'str' does not support the buffer interface

**Comment by kmaehashi** [comment]
fixed.

**Comment by kmaehashi** [comment]
In the meeting on 2015/07/21 we decided not to wait https://github.com/tanakh/waf-unittest/pull/18 merge.

**Comment by rimms** [comment]
:+1:  I tested this patch with Python 3.4.2.

```
$ ./waf cofigure
... snip ...
'configure' finished successfully (0.981s)
$ ./waf build --checkall
... snip ...
'build' finished successfully (15.155s)
$ ./waf cpplint
... snip ...
'cpplint' finished successfully (7.554s)
$ ./waf install
... snip ...
'install' finished successfully (1.834s)
```

**Pull request merged**
